apiVersion: v1
kind: ConfigMap
metadata:
  name: gocd-init-configmap
data:
  addon_config.sh: |-
    #!bin/bash
     
    SERVICE_ACCOUNT_PATH=/var/run/secrets/kubernetes.io/serviceaccount
    KUBE_TOKEN=$(<${SERVICE_ACCOUNT_PATH}/token)

    tee /godata/config/postgresqldb.properties >/dev/null <<EOF
    db.host=postgresdb-postgresql
    db.port=5432
    db.name=cruise
    db.user=postgres
    db.password=postgres
    EOF
   
    curl -L -o '/godata/addons/go-postgresql.jar' --fail -H 'Accept: binary/octet-stream' --user $EXTENSION_USERNAME:$EXTENSION_PASSWORD \
    'https://extensions.gocd.org/addons/postgres_experimental/versions/latest/download?eula_accepted=true' &> /godata/addons/addon_config.log
